name: Feature Request
description: Provide ideas for us.
title: "[Feature] Input Your Title"
labels:
  - "enhancement"
assignees: TuanZiGit
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: Describe what problem you want to fix / what feature you want to add.
  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: Solutions
      description: What you want to see?
      placeholder: |
        What you hope to see? How can we do that?
  - type: textarea
    id: fallback
    attributes:
      label: Alternative Solutions
      description: Can we use another solution if we can't do that?
  - type: textarea
    id: additional
    attributes:
      label: Additional Informations
      description: Add things you think that's important.